### ISSUE TITLE
why did this error occur

### ISSUE THREAD

**Issue by wangfeifeifeifei** [BanaanKiamanesh/Pose-Ordered-Tello#1]
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Pose-Ordered-Tello-main\Main.py", line 41, in <module>
    with mp.solutions.pose.Pose(
  File "F:\anaconda3\envs\tellopose\lib\site-packages\mediapipe\python\solutions\pose.py", line 145, in __init__
    _download_oss_pose_landmark_model(model_complexity)
  File "F:\anaconda3\envs\tellopose\lib\site-packages\mediapipe\python\solutions\pose.py", line 100, in _download_oss_pose_landmark_model
    download_utils.download_oss_model(
  File "F:\anaconda3\envs\tellopose\lib\site-packages\mediapipe\python\solutions\download_utils.py", line 32, in download_oss_model
    with urllib.request.urlopen(model_url) as response, open(model_abspath,
  File "F:\anaconda3\envs\tellopose\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "F:\anaconda3\envs\tellopose\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "F:\anaconda3\envs\tellopose\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "F:\anaconda3\envs\tellopose\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "F:\anaconda3\envs\tellopose\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "F:\anaconda3\envs\tellopose\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
[INFO] tello.py - 437 - Send command: 'streamoff'
[INFO] tello.py - 461 - Response streamoff: 'ok'

**Comment by BanaanKiamanesh** [comment]
Hi, hope you are doing well.
Mediapipe has 3 AI models for its detection. It is specified by model
complexity. you can set it from 0 to 2. but! you have to download the
models first.

Simplest way of doing it is by copying the sample code from mediapipe pose
section and setting model complexity from 0 to 2 and running the code once
for each model with a normal webcam(not on the quadcopter). it will
automatically download the required models. Just make sure you have an
internet access to your computer.

hope this helps :)
